### PR TITLE
Configure Maven Central deployment

### PR DESCRIPTION
**Pull request by joshmoore**
* [x] Apply similar changes to https://github.com/zarr-developers/jzarr/pull/1
 * [x] Configure OSSRH_USERNAME and OSSRH_TOKEN using my https://s01.oss.sonatype.org account
 * [x] Bump to 0.0.1 for release

### CODE REVIEW

**Comment by joshmoore** [comment]
Based on the screenshot below and the fact that I would need to contact someone to migrate our namespace, I'm trying the old method with this PR with the hope that we can keep using it for a while.

image

**Comment by joshmoore** [comment]
Note: I've updated the release here to 0.0.1. Last time, it took me several versions to get Maven Central passing, so I might be quickly drafting a 0.0.2, 0.0.3, etc.

Please let me know if there are any objections to this.

cc: @normanrz @sbesson @melissalinkert

**Comment by sbesson** [comment]
> Note: I've updated the release here to 0.0.1.

Phew! Since the commit message says "Bump to 1.0.0" 😄

**Comment by joshmoore** [comment]
Doh! I'll force push. 🤦🏽

**Comment by joshmoore** [comment]
Ok. That's a :+1: from GS and SM and the builds are green. Moving forward with a series of attempted releases to see if I can get this working.

**Review by sbesson — APPROVED** [review]

**Comment by joshmoore** [comment]
Release failed with:

```
java.io.IOException: Cannot run program "venv_zarrita/bin/python": error=2, No such file or directory
```

see: https://github.com/scalableminds/zarr-java2/pull/5/commits/22b55149cae1e15eb540a2ef1aa7abf28121d58e

**Comment by joshmoore** [comment]
Hurrah! https://central.sonatype.com/artifact/dev.zarr/zarr-java

**Comment by normanrz** [comment]
Very cool, thanks!

**Pull request merged**
