### PR TITLE
Check sharding bounds

### LINKED ISSUE #5: Attempting to write with sharding throws `ArrayIndexOutOfBoundsException`
I'm in the process of adding sharding options to https://github.com/glencoesoftware/zarr2zarr, but am having a difficult time figuring out how to configure sharding so that chunks can be written without throwing an exception.

A small example, where I'd expect 4 shards total, each containing 4 chunks:

```
FilesystemStore outputStore = new FilesystemStore("tiny-test.zarr");

// 4x4 image
long[] shape = new long[] {4, 4};
// 1x1 chunks == 1 pixel per chunk, expect 16 chunks total
int[] chunkSize = new int[] {1, 1};
// expect 2x2 chunks per shard, 2x2 shards in the image
int[] shardSize = new int[] {2, 2};

Array outputArray = Array.create(outputStore.resolve("0", "0"),
    Array.metadataBuilder()
        .withShape(shape)
        .withDataType(dev.zarr.zarrjava.v3.DataType.UINT8)
        .withChunkShape(chunkSize)
        .withFillValue(255)
        .withCodecs(c -> c.withSharding(shardSize))
        .build()
);

for (int y=0; y<shape[0]; y+=chunkSize[0]) {
    for (int x=0; x<shape[1]; x+=chunkSize[1]) {
        outputArray.write(new long[]{y, x},
            ucar.ma2.Array.factory(ucar.ma2.DataType.UBYTE, chunkSize)
        );
    }
} 
```

If I run that as-is, using zarr-java 0.0.2, it throws an exception during array writing:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at ucar.ma2.Index3D.set0(Index3D.java:86)
	at ucar.ma2.Index3D.set(Index3D.java:115)
	at dev.zarr.zarrjava.v3.codec.core.ShardingIndexedCodec.setValueFromShardIndexArray(ShardingIndexedCodec.java:92)
	at dev.zarr.zarrjava.v3.codec.core.ShardingIndexedCodec.lambda$encode$1(ShardingIndexedCodec.java:141)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at dev.zarr.zarrjava.v3.codec.core.ShardingIndexedCodec.encode(ShardingIndexedCodec.java:116)
	at dev.zarr.zarrjava.v3.codec.CodecPipeline.encode(CodecPipeline.java:145)
	at dev.zarr.zarrjava.v3.Array.writeChunk(Array.java:301)
	at dev.zarr.zarrjava.v3.Array.lambda$write$1(Array.java:279)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at dev.zarr.zarrjava.v3.Array.write(Array.java:257)
```

If I replace `int[] shardSize = new int[] {2, 2};` with `int[] shardSize = new int[] {1, 1};` in the test code, though, then there is no exception and I get the expected output, which is one shard == one chunk. I don't know if this is an issue with zarr-java, or if I'm just misunderstanding something and need to fix the test code - either way, any ideas would be much appreciated.

### PR DESCRIPTION
**Pull request by brokkoli71**
fixes #5 

this PR implements checks if the dataset shape, shard shape, (nested shard shapes) and chunk shape are compatible with each other

### CODE REVIEW

**Review by normanrz — COMMENTED** [review]
I wonder if this should also be checked in ArrayMetadata? Imaginge someone uses teh ArrayMetadata constructure directly or creates a faulty zarr.json that zarr-java reads.

**Comment by brokkoli71** [comment]
> I wonder if this should also be checked in ArrayMetadata? Imaginge someone uses teh ArrayMetadata constructure directly or creates a faulty zarr.json that zarr-java reads.

Good idea, I will move the checks into the ArrayMetadata constructor. Then, they will be called in all three cases

**Review by normanrz — APPROVED** [review]
Looks good!
Maybe as a follow-up, you could go through some of the other validations we have in zarr-python:
https://github.com/zarr-developers/zarr-python/blob/v3/src/zarr/codecs/pipeline.py#L471
https://github.com/zarr-developers/zarr-python/blob/v3/src/zarr/codecs/transpose.py#L49
https://github.com/zarr-developers/zarr-python/blob/v3/src/zarr/core/metadata.py#L213

**Review by sbesson — APPROVED** [review]
Thanks @brokkoli71, as we are exploring how user would specific shard sizes via options, it is really useful that the `ArrayMetadataBuilder` API include some validation of the various chunk sizes.

In addition to the test case introduced in this PR, can I also offer https://github.com/sbesson/zarr-java/commit/bf3f08ffac99c7208f092090a20f975b9b8a64f6 which should test the validation in the non-sharding scenario. The first two parametrized tests should pass with the current HEAD of zarr-java (as per the mismatching number of dimensions) and the two additional tests are now covered by the extra checks introduced in this PR

**Comment by brokkoli71** [comment]
Thanks for the test @sbesson, I merged it to this branch.

Seems like a good addition @normanrz, I will have a look at it

**Comment by sbesson** [comment]
After including the latest release for a round of functional testing, I realised that the containment check introduced in this PR enforces that for every dimension `i`

```
array_shape[i] >= outer_chunk[i] (if applicable) >= inner_chunk[i]
```

This constraint is critical when writing multiscale groups as defined in the OME-NGFF specification where the shape of each array is reduced alongside 2 or more dimensions and the chunk/shard shape might be kept constant.

Taking the concrete example of one of [the Zarr dataset](https://deploy-preview-36--ome-ngff-validator.netlify.app/?source=https://uk1s3.embassy.ebi.ac.uk/idr/share/ome2024-ngff-challenge/0.0.5/9822152.zarr) converted as part of the OME NGFF 2024 challenge using zarr-python, the [11th resolution of the multiscale group](https://uk1s3.embassy.ebi.ac.uk/idr/share/ome2024-ngff-challenge/0.0.5/9822152.zarr/10/zarr.json) has the following array metadata

```json
{
  "chunk_grid": {
    "configuration": {
      "chunk_shape": [
        1,
        1,
        1,
        4096,
        4096
      ]
    },
    "name": "regular"
  },
  "chunk_key_encoding": {
    "name": "default"
  },
  "codecs": [
    {
      "configuration": {
        "chunk_shape": [
          1,
          1,
          1,
          1024,
          1024
        ],
        "codecs": [
          {
            "configuration": {
              "endian": "little"
            },
            "name": "bytes"
          },
          {
            "configuration": {
              "blocksize": 0,
              "clevel": 5,
              "cname": "zstd",
              "shuffle": "shuffle",
              "typesize": 2
            },
            "name": "blosc"
          }
        ],
        "index_codecs": [
          {
            "configuration": {
              "endian": "little"
            },
            "name": "bytes"
          },
          {
            "name": "crc32c"
          }
        ]
      },
      "name": "sharding_indexed"
    }
  ],
  "data_type": "uint16",
  "dimension_names": [
    "t",
    "c",
    "z",
    "y",
    "x"
  ],
  "fill_value": 0,
  "node_type": "array",
  "shape": [
    1,
    1,
    1,
    91,
    141
  ],
  "zarr_format": 3
}
```

With this change, such metadata cannot be written using zarr-java. This feels at odds with the [Zarr v3 specification](https://zarr-specs.readthedocs.io/) where I see two main constraints around shape sizes:
- the length of the array shape, chunk shape and shard shape (if applicable) must be the same 
- the inner chunk shape along each dimension must evenly divide the size of the shard shape - https://zarr-specs.readthedocs.io/en/latest/v3/codecs/sharding-indexed/v1.0.html

/cc @melissalinkert @joshmoore

**Comment by normanrz** [comment]
I think that constraint is too strict. The array size is independent of the chunk size (except that they need to have the same number of dimensions). For sharding, inner chunk sizes need to evenly divide the outer chunk sizes, which implies inner_chunk[i] <= outer_chunk[i].
@brokkoli71 Could you have a look at this please?

**Comment by brokkoli71** [comment]
right, @sbesson. I have changed the bounds check in #9

**Pull request merged**
